const mongoose = require("mongoose")

// ./mongod --dbpath ~/mongo-data

mongoose.connect("mongodb://127.0.0.1:27017/Kurye-Taxi-DB",{
    useNewUrlParser : true,
    useCreateIndex : true,
    useFindAndModify : false    
})


// Socket {
//     nsp:
//      Namespace {
//        name: '/',
//        server:
//         Server {
//           nsps: [Object],
//           parentNsps: Map {},
//           _path: '/socket.io',
//           _serveClient: true,
//           parser: [Object],
//           encoder: Encoder {},
//           _adapter: [Function: Adapter],
//           _origins: '*:*',
//           sockets: [Circular],
//           eio: [Server],
//           httpServer: [Server],
//           engine: [Server] },
//        sockets: { 'l1u-9DzmjL-xpl9LAAAA': [Circular] },
//        connected: { 'l1u-9DzmjL-xpl9LAAAA': [Circular] },
//        fns: [],
//        ids: 0,
//        rooms: [],
//        flags: {},
//        adapter:
//         Adapter {
//           nsp: [Circular],
//           rooms: [Object],
//           sids: [Object],
//           encoder: Encoder {} },
//        _events: { connection: [Function] },
//        _eventsCount: 1 },
//     server:
//      Server {
//        nsps: { '/': [Namespace] },
//        parentNsps: Map {},
//        _path: '/socket.io',
//        _serveClient: true,
//        parser:
//         { protocol: 4,
//           types: [Array],
//           CONNECT: 0,
//           DISCONNECT: 1,
//           EVENT: 2,
//           ACK: 3,
//           ERROR: 4,
//           BINARY_EVENT: 5,
//           BINARY_ACK: 6,
//           Encoder: [Function: Encoder],
//           Decoder: [Function: Decoder] },
//        encoder: Encoder {},
//        _adapter: [Function: Adapter],
//        _origins: '*:*',
//        sockets:
//         Namespace {
//           name: '/',
//           server: [Circular],
//           sockets: [Object],
//           connected: [Object],
//           fns: [],
//           ids: 0,
//           rooms: [],
//           flags: {},
//           adapter: [Adapter],
//           _events: [Object],
//           _eventsCount: 1 },
//        eio:
//         Server {
//           clients: [Object],
//           clientsCount: 1,
//           wsEngine: 'ws',
//           pingTimeout: 5000,
//           pingInterval: 25000,
//           upgradeTimeout: 10000,
//           maxHttpBufferSize: 100000000,
//           transports: [Array],
//           allowUpgrades: true,
//           allowRequest: [Function: bound ],
//           cookie: 'io',
//           cookiePath: '/',
//           cookieHttpOnly: true,
//           perMessageDeflate: [Object],
//           httpCompression: [Object],
//           initialPacket: [Array],
//           ws: [WebSocketServer],
//           _events: [Object],
//           _eventsCount: 1 },
//        httpServer:
//         Server {
//           _events: [Object],
//           _eventsCount: 5,
//           _maxListeners: undefined,
//           _connections: 1,
//           _handle: [TCP],
//           _usingWorkers: false,
//           _workers: [],
//           _unref: false,
//           allowHalfOpen: true,
//           pauseOnConnect: false,
//           httpAllowHalfOpen: false,
//           timeout: 120000,
//           keepAliveTimeout: 5000,
//           _pendingResponseData: 0,
//           maxHeadersCount: null,
//           headersTimeout: 40000,
//           _connectionKey: '6::::8000',
//           [Symbol(IncomingMessage)]: [Function],
//           [Symbol(ServerResponse)]: [Function],
//           [Symbol(asyncId)]: 12 },
//        engine:
//         Server {
//           clients: [Object],
//           clientsCount: 1,
//           wsEngine: 'ws',
//           pingTimeout: 5000,
//           pingInterval: 25000,
//           upgradeTimeout: 10000,
//           maxHttpBufferSize: 100000000,
//           transports: [Array],
//           allowUpgrades: true,
//           allowRequest: [Function: bound ],
//           cookie: 'io',
//           cookiePath: '/',
//           cookieHttpOnly: true,
//           perMessageDeflate: [Object],
//           httpCompression: [Object],
//           initialPacket: [Array],
//           ws: [WebSocketServer],
//           _events: [Object],
//           _eventsCount: 1 } },
//     adapter:
//      Adapter {
//        nsp:
//         Namespace {
//           name: '/',
//           server: [Server],
//           sockets: [Object],
//           connected: [Object],
//           fns: [],
//           ids: 0,
//           rooms: [],
//           flags: {},
//           adapter: [Circular],
//           _events: [Object],
//           _eventsCount: 1 },
//        rooms: { 'l1u-9DzmjL-xpl9LAAAA': [Room] },
//        sids: { 'l1u-9DzmjL-xpl9LAAAA': [Object] },
//        encoder: Encoder {} },
//     id: 'l1u-9DzmjL-xpl9LAAAA',
//     client:
//      Client {
//        server:
//         Server {
//           nsps: [Object],
//           parentNsps: Map {},
//           _path: '/socket.io',
//           _serveClient: true,
//           parser: [Object],
//           encoder: Encoder {},
//           _adapter: [Function: Adapter],
//           _origins: '*:*',
//           sockets: [Namespace],
//           eio: [Server],
//           httpServer: [Server],
//           engine: [Server] },
//        conn:
//         Socket {
//           id: 'l1u-9DzmjL-xpl9LAAAA',
//           server: [Server],
//           upgrading: false,
//           upgraded: false,
//           readyState: 'open',
//           writeBuffer: [],
//           packetsFn: [],
//           sentCallbackFn: [],
//           cleanupFn: [Array],
//           request: [IncomingMessage],
//           remoteAddress: '::ffff:127.0.0.1',
//           checkIntervalTimer: null,
//           upgradeTimeoutTimer: null,
//           pingTimeoutTimer:
//            Timeout {
//              _called: false,
//              _idleTimeout: 30000,
//              _idlePrev: [TimersList],
//              _idleNext: [TimersList],
//              _idleStart: 3390,
//              _onTimeout: [Function],
//              _timerArgs: undefined,
//              _repeat: null,
//              _destroyed: false,
//              [Symbol(unrefed)]: false,
//              [Symbol(asyncId)]: 45,
//              [Symbol(triggerId)]: 40 },
//           transport: [XHR],
//           _events: [Object],
//           _eventsCount: 3 },
//        encoder: Encoder {},
//        decoder: Decoder { reconstructor: null, _callbacks: [Object] },
//        id: 'l1u-9DzmjL-xpl9LAAAA',
//        request:
//         IncomingMessage {
//           _readableState: [ReadableState],
//           readable: true,
//           _events: {},
//           _eventsCount: 0,
//           _maxListeners: undefined,
//           socket: [Socket],
//           connection: [Socket],
//           httpVersionMajor: 1,
//           httpVersionMinor: 1,
//           httpVersion: '1.1',
//           complete: true,
//           headers: [Object],
//           rawHeaders: [Array],
//           trailers: {},
//           rawTrailers: [],
//           aborted: false,
//           upgrade: false,
//           url: '/socket.io/?EIO=3&transport=polling&t=MoMxIV2',
//           method: 'GET',
//           statusCode: null,
//           statusMessage: null,
//           client: [Socket],
//           _consuming: false,
//           _dumped: true,
//           _query: [Object],
//           res: [ServerResponse],
//           cleanup: [Function: cleanup] },
//        onclose: [Function: bound ],
//        ondata: [Function: bound ],
//        onerror: [Function: bound ],
//        ondecoded: [Function: bound ],
//        sockets: { 'l1u-9DzmjL-xpl9LAAAA': [Circular] },
//        nsps: { '/': [Circular] },
//        connectBuffer: [] },
//     conn:
//      Socket {
//        id: 'l1u-9DzmjL-xpl9LAAAA',
//        server:
//         Server {
//           clients: [Object],
//           clientsCount: 1,
//           wsEngine: 'ws',
//           pingTimeout: 5000,
//           pingInterval: 25000,
//           upgradeTimeout: 10000,
//           maxHttpBufferSize: 100000000,
//           transports: [Array],
//           allowUpgrades: true,
//           allowRequest: [Function: bound ],
//           cookie: 'io',
//           cookiePath: '/',
//           cookieHttpOnly: true,
//           perMessageDeflate: [Object],
//           httpCompression: [Object],
//           initialPacket: [Array],
//           ws: [WebSocketServer],
//           _events: [Object],
//           _eventsCount: 1 },
//        upgrading: false,
//        upgraded: false,
//        readyState: 'open',
//        writeBuffer: [],
//        packetsFn: [],
//        sentCallbackFn: [],
//        cleanupFn: [ [Function], [Function] ],
//        request:
//         IncomingMessage {
//           _readableState: [ReadableState],
//           readable: true,
//           _events: {},
//           _eventsCount: 0,
//           _maxListeners: undefined,
//           socket: [Socket],
//           connection: [Socket],
//           httpVersionMajor: 1,
//           httpVersionMinor: 1,
//           httpVersion: '1.1',
//           complete: true,
//           headers: [Object],
//           rawHeaders: [Array],
//           trailers: {},
//           rawTrailers: [],
//           aborted: false,
//           upgrade: false,
//           url: '/socket.io/?EIO=3&transport=polling&t=MoMxIV2',
//           method: 'GET',
//           statusCode: null,
//           statusMessage: null,
//           client: [Socket],
//           _consuming: false,
//           _dumped: true,
//           _query: [Object],
//           res: [ServerResponse],
//           cleanup: [Function: cleanup] },
//        remoteAddress: '::ffff:127.0.0.1',
//        checkIntervalTimer: null,
//        upgradeTimeoutTimer: null,
//        pingTimeoutTimer:
//         Timeout {
//           _called: false,
//           _idleTimeout: 30000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 3390,
//           _onTimeout: [Function],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(unrefed)]: false,
//           [Symbol(asyncId)]: 45,
//           [Symbol(triggerId)]: 40 },
//        transport:
//         XHR {
//           readyState: 'open',
//           discarded: false,
//           closeTimeout: 30000,
//           maxHttpBufferSize: 100000000,
//           httpCompression: [Object],
//           supportsBinary: true,
//           _events: [Object],
//           _eventsCount: 5,
//           sid: 'l1u-9DzmjL-xpl9LAAAA',
//           req: null,
//           res: null,
//           writable: false },
//        _events:
//         { close: [Array],
//           data: [Function: bound ],
//           error: [Function: bound ] },
//        _eventsCount: 3 },
//     rooms: {},
//     acks: {},
//     connected: true,
//     disconnected: false,
//     handshake:
//      { headers:
//         { host: '127.0.0.1:8000',
//           connection: 'keep-alive',
//           accept: '*/*',
//           'user-agent':
//            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3882.0 Safari/537.36',
//           'sec-fetch-mode': 'cors',
//           origin: 'http://localhost:3000',
//           'sec-fetch-site': 'cross-site',
//           referer: 'http://localhost:3000/cagir',
//           'accept-encoding': 'gzip, deflate, br',
//           'accept-language': 'tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7',
//           cookie: 'io=47AH17x2iYrRXzYAAAAD' },
//        time: 'Thu Aug 15 2019 23:17:00 GMT+0300 (GMT+03:00)',
//        address: '::ffff:127.0.0.1',
//        xdomain: true,
//        secure: false,
//        issued: 1565900220374,
//        url: '/socket.io/?EIO=3&transport=polling&t=MoMxIV2',
//        query: { EIO: '3', transport: 'polling', t: 'MoMxIV2' } },
//     fns: [],
//     flags: {},
//     _rooms: [] }